#include	<YSI_Coding\y_hooks>

enum 
{
 	DIALOG_REGISTRO,
 	DIALOG_LOGIN,
    DIALOG_IDADE,
    DIALOG_SEXO,
    DIALOG_SKIN,
 	DIALOG_DEPOSITAR,
 	DIALOG_SACAR,
 	DIALOG_SALDO,
 	DIALOG_IDTRANFERIR,
 	DIALOG_TRANSFERIR,
	DIALOG_TELEMARK,
	DIALOG_AA,
	DIALOG_CARRO_ADM,
	DIALOG_VERINFO,
	DIALOG_MUDARSEXO,
	DIALOG_AJUDA,
	DIALOG_AJUDACOMANDOS,
	DIALOG_AJUDAEMPREGO,
	D_CONCECARRO,
	D_CONCEMOTO,
	D_MENUCAR,
	D_CONCE
};